pipeline {
    agent any
    stages {
        stage("Build") {
           steps {
              sh label: '', script: '''
              chmod +x gradlew
              ./gradlew jar
              '''
           }
        }

        stage("Test") {
           steps {
               sh label: '', script: '''
              chmod +x gradlew
              ./gradlew test
              '''
           }
        }

        stage("Static Code Analysis") {
           steps {
               echo "TODO: Analyse Static code"
           }
        }

        stage("Create Docker Image") {
           steps {
               sh label: '', script: '''
                docker build -f ".infra/docker/Dockerfile" -t httpserver:v0.0 . 
               '''
           }
        }

        stage("Publish Docker Image") {
           steps {
               sh label: '', script: '''
                docker login -u bibekbc4 -p zaq1ZAQ!zaq1 dockerio
                docker tag httpserver:v0.0 bibekbc4/httpserver
                docker push bibekbc4/httpserver
               '''
           }
        }
    } 
    post {
        always {
            sh label: '', script: 'docker logout'
            deleteDir()
        }
    }
}
